"""cria tabela devices

Revision ID: 98c979b4f8dd
Revises: 
Create Date: 2026-09-07 06:11:31.412448
"""
from alembic import op
import sqlalchemy as sa

import app.core.types


revision = '98c979b4f8dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('DESKTOP', 'NOTEBOOK', 'SERVIDOR', 'IMPRESSORA', 'MONITOR', 'OUTRO', name='devicetype'), nullable=False),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('EM_USO', 'ESTOQUE', 'MANUTENCAO', 'BAIXADO', name='devicestatus'), nullable=False),
    sa.Column('localizacao', sa.String(length=120), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('installed_software',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('device_id', app.core.types.GUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('versao', sa.String(length=50), nullable=True),
    sa.Column('data_instalacao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('device_id', app.core.types.GUID(), nullable=False),
    sa.Column('descricao', sa.String(length=2000), nullable=False),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    op.drop_table('installed_software')
    op.drop_table('devices')
    # ### end Alembic commands ###
